name: first workflow
on:
  push:
    branches: [main]       # ✅ main 브랜치로 푸시될 때 자동 실행
  workflow_dispatch:  
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, World!"
